services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fintech_etl
    volumes:
      - "fintech_etl_postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"    
    networks:
      - airflow

volumes:
  fintech_etl_postgres:

networks:
  airflow:
    external:
      name: airflow_default  
